/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    products: Product;
    subcategories: Subcategory;
    media: Media;
    "callback-requests": CallbackRequest;
    users: User;
    consents: Consent;
    "media-galleries": MediaGallery;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    "callback-requests":
      | CallbackRequestsSelect<false>
      | CallbackRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    "media-galleries": MediaGalleriesSelect<false> | MediaGalleriesSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ("false" | "none" | "null")
    | false
    | null
    | ("ru" | "en")
    | ("ru" | "en")[];
  globals: {
    settings: Setting;
    "home-content": HomeContent;
    "about-content": AboutContent;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    "home-content": HomeContentSelect<false> | HomeContentSelect<true>;
    "about-content": AboutContentSelect<false> | AboutContentSelect<true>;
  };
  locale: "ru" | "en";
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  /**
   * Автоматически генерируется из названия
   */
  slug: string;
  image: string | Media;
  description?: string | null;
  order?: number | null;
  isPublished?: boolean | null;
  /**
   * Показывается увеличенной карточкой в начале списка на главной странице
   */
  featured?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: знаки, светофоры, дорожные ограждения
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  type?:
    | (
        | "certificate"
        | "instruction"
        | "license"
        | "passport"
        | "product"
        | "hero"
        | "other"
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  images: (string | Media)[];
  description: string;
  category: string | Category;
  subcategory?: (string | null) | Subcategory;
  price?: number | null;
  showPrice?: boolean | null;
  useVariants?: boolean | null;
  variantGroups?:
    | {
        label: string;
        displayType: "list" | "dropdown";
        code?: string | null;
        values: {
          label: string;
          code?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  variantCombinations?:
    | {
        label?: string | null;
        price?: number | null;
        key: string;
        id?: string | null;
      }[]
    | null;
  attributes?:
    | {
        title: string;
        values?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        file: string | Media;
        id?: string | null;
      }[]
    | null;
  badges?: ("new" | "hit" | "sale" | "gost")[] | null;
  /**
   * Выберите товары, которые будут показаны в блоке "Рекомендуемые" на странице этого товара. Порядок важен.
   */
  recommendedProducts?: (string | Product)[] | null;
  order?: number | null;
  isPublished?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: знаки, светофоры, дорожные ограждения
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: string;
  name: string;
  category: string | Category;
  order?: number | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callback-requests".
 */
export interface CallbackRequest {
  id: string;
  name?: string | null;
  phone: string;
  email?: string | null;
  comment?: string | null;
  subject?: string | null;
  productTitle?: string | null;
  productSku?: string | null;
  status?: ("new" | "processing" | "completed") | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: "admin" | "manager";
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: string;
  title: string;
  /**
   * Автоматически генерируется из названия
   */
  slug: string;
  /**
   * Показывается в списке на странице /consents
   */
  excerpt?: string | null;
  /**
   * Полный текст. Разделяйте абзацы пустой строкой.
   */
  content: string;
  /**
   * Внешняя ссылка на документ (например, на Яндекс.Диск). Файл не хранится в проекте — используется только URL, указанный здесь.
   */
  documentUrl?: string | null;
  /**
   * Например: «Скачать PDF». Необязательно.
   */
  documentLabel?: string | null;
  order?: number | null;
  isPublished?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: знаки, светофоры, дорожные ограждения
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Универсальные медиа-подборки для блоков сайта (сертификаты, отзывы и т.д.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-galleries".
 */
export interface MediaGallery {
  id: string;
  /**
   * Стабильный технический идентификатор, например "certificates" или "reviews". По нему блок ищется на фронтенде — после создания лучше не менять.
   */
  key: string;
  label: string;
  title?: string | null;
  description?: string | null;
  /**
   * Порядок в списке = порядок отображения. Перетаскивайте для сортировки.
   */
  items?:
    | {
        image: string | Media;
        /**
         * Необязательно. Если не указано — используется Alt файла.
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: "categories";
        value: string | Category;
      } | null)
    | ({
        relationTo: "products";
        value: string | Product;
      } | null)
    | ({
        relationTo: "subcategories";
        value: string | Subcategory;
      } | null)
    | ({
        relationTo: "media";
        value: string | Media;
      } | null)
    | ({
        relationTo: "callback-requests";
        value: string | CallbackRequest;
      } | null)
    | ({
        relationTo: "users";
        value: string | User;
      } | null)
    | ({
        relationTo: "consents";
        value: string | Consent;
      } | null)
    | ({
        relationTo: "media-galleries";
        value: string | MediaGallery;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: "users";
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  description?: T;
  order?: T;
  isPublished?: T;
  featured?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  images?: T;
  description?: T;
  category?: T;
  subcategory?: T;
  price?: T;
  showPrice?: T;
  attributes?:
    | T
    | {
        title?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  documents?:
    | T
    | {
        file?: T;
        id?: T;
      };
  badges?: T;
  recommendedProducts?: T;
  order?: T;
  isPublished?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callback-requests_select".
 */
export interface CallbackRequestsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  comment?: T;
  subject?: T;
  productTitle?: T;
  productSku?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  documentUrl?: T;
  documentLabel?: T;
  order?: T;
  isPublished?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-galleries_select".
 */
export interface MediaGalleriesSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  title?: T;
  description?: T;
  items?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  companyName: string;
  companyEmail?: string | null;
  logo: string | Media;
  managers?:
    | {
        name: string;
        email: string;
        phone: string;
        order?: number | null;
        id?: string | null;
      }[]
    | null;

  contacts?:
    | {
        title: string;
        value: string;
        type?:
          | ("text" | "phone" | "email" | "link" | "whatsapp" | "telegram")
          | null;
        icon?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        title?: string | null;
        url: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  workingHours?: string | null;
  map?: string | null;
  heroBackground?: {
    type?: ("none" | "image" | "video") | null;
    image?: (string | null) | Media;
    video?: (string | null) | Media;
    videoPoster?: (string | null) | Media;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Пример: знаки, светофоры, дорожные ограждения
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  logo?: T;
  contacts?:
    | T
    | {
        title?: T;
        value?: T;
        type?: T;
        icon?: T;
        order?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        title?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  workingHours?: T;
  map?: T;
  heroBackground?:
    | T
    | {
        type?: T;
        image?: T;
        video?: T;
        videoPoster?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 *
 * NOTE: `payload generate:types` currently fails in this environment with
 * `ERR_MODULE_NOT_FOUND: Cannot find package '@/services'` (pre-existing,
 * reproducible on master before this change — unrelated to home-content/
 * about-content). This interface was written by hand to match
 * src/payload/globals/HomeContent.ts field-for-field; re-running
 * `generate:types` once that issue is fixed will regenerate it and should
 * produce an equivalent shape.
 */
export interface HomeContent {
  id: string;
  aboutIntro?: {
    eyebrow: string;
    heading: string;
    lead: string;
    image?: (string | null) | Media;
    imageAlt: string;
  };
  /**
   * Блок из карточек перед секцией «Почему выбирают СТК-Актив». Количество карточек должно быть чётным — на десктопе они располагаются по 2 в ряд.
   */
  featureCards?:
    | {
        image: string | Media;
        title: string;
        description: string;
        buttonText: string;
        link?: {
          type: "internal" | "external";
          url: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  aboutIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        image?: T;
        imageAlt?: T;
      };
  featureCards?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        buttonText?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 *
 * NOTE: hand-written — see the comment on `HomeContent` above.
 */
export interface AboutContent {
  id: string;

  hero?: {
    eyebrow: string;
    heading: string;
    lead: string;
    image?: (string | null) | Media;
    imageAlt: string;
  };

  mediaBlocks?:
    | {
        eyebrow?: string | null;
        heading: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        images?:
          | {
              image?: (string | null) | Media;
              alt: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;

  callout?: {
    text: string;
  };

  production?: {
    heading: string;
    subheading: string;
    steps?:
      | {
          title: string;
          description: string;
          icon: "cut" | "apply" | "assemble" | "inspect" | "pack";
          id?: string | null;
        }[]
      | null;
  };

  productionWater?: {
    heading: string;
    subheading: string;
    steps?:
      | {
          title: string;
          description: string;
          icon: "cut" | "apply" | "assemble" | "inspect" | "pack";
          id?: string | null;
        }[]
      | null;
  };

  standards?: {
    heading: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;

    materials?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;

    filmBrands?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };

  quality?: {
    heading: string;
    subheading: string;

    checks?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };

  geography?: {
    heading: string;
    subheading: string;
    regionsCount: string;

    image?: (string | null) | Media;

    routes?:
      | {
          name: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };

  timeline?: {
    heading: string;
    subheading: string;

    events?:
      | {
          year: string;
          title: string;
          description: string;
          highlight?: string | null;
          id?: string | null;
        }[]
      | null;
  };

  directions?: {
    heading: string;

    items?:
      | {
          title: string;
          description: string;
          href: string;
          image?: (string | null) | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };

  updatedAt?: string | null;
  createdAt?: string | null;
} /**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lead?: T;
        image?: T;
        imageAlt?: T;
      };
  mediaBlocks?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        id?: T;
      };
  callout?:
    | T
    | {
        text?: T;
      };
  production?:
    | T
    | {
        heading?: T;
        subheading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  productionWater?:
    | T
    | {
        heading?: T;
        subheading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  standards?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        materials?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        filmBrands?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  quality?:
    | T
    | {
        heading?: T;
        subheading?: T;
        checks?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  geography?:
    | T
    | {
        heading?: T;
        subheading?: T;
        regionsCount?: T;
        image?: T;
        routes?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        heading?: T;
        subheading?: T;
        events?:
          | T
          | {
              year?: T;
              title?: T;
              description?: T;
              highlight?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
